name: Release PyPI, installers and docker container

on:
  push:
    tags: "v*"

jobs:
  release_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Install dependencies
        run: |
          pip install .
          pip freeze > requirements.txt
      - name: Publish Latest Draft
        run: |
          # Get the latest draft release
          RELEASE_DATA=$(gh api repos/:owner/:repo/releases | jq '[.[] | select(.draft == true)][0]')
          RELEASE_ID=$(echo $RELEASE_DATA | jq '.id')

          # Publish the release
          gh api -X PATCH repos/:owner/:repo/releases/$RELEASE_ID --field draft=false
          gh release upload ${{ github.ref }} requirements.txt --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
